# builder
FROM golang:alpine as builder

#ENV GOPROXY=https://goproxy.cn,direct
WORKDIR /app

RUN apk add --no-cache git  && git clone https://github.com/AdguardTeam/dnsproxy.git . && \
    go mod download && \
    go build -o dnsproxy .

# runner
FROM alpine:latest as runner

# 声明服务端口
EXPOSE 1853
# 启动应用程序
CMD ["./dnsproxy", "-l", "0.0.0.0", "-p", "1853", "-u", "8.8.8.8:53", "-u", "8.8.4.4:53", "-u", "1.1.1.1:53", "--cache", "--cache-min-ttl=10", "--cache-max-ttl=600", "--fastest-addr", "-v", "-o", "dnsproxy.log"]